config/routes.rb
Sosbichos::Application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :profiles
  end

  resources :profiles
  root :to => "home#index"
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  validates_presence_of :name

  def to_s
    name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :confirmable, 
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me


end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
  before_filter :authenticate_user!
end

app/controllers/admin/profiles_controller.rb
class Admin::ProfilesController < Admin::BaseController
  before_filter :build_object, :only => [:new, :create]
  before_filter :find_object, :only => [:show, :edit, :update, :destroy]

  def index
    @profiles = Profile.all
    respond_with @profiles
  end

  def show
  end

  def new
  end

  def create
    @profile.save!
    respond_with_profiles_collection
  end

  def edit
  end

  def update
    @profile.update_attributes(params[:profile])
    respond_with_profiles_collection
  end

  def destroy
    @profile.destroy
    respond_with_profiles_collection
  end


  private
  def find_object
    @profile = Profile.find(params[:id])
  end

  def build_object
    @profile = Profile.new(params[:profile])
  end

  def respond_with_profiles_collection
    respond_with @profile, :location => admin_profiles_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  self.responder = ApplicationResponder
  self.respond_to :html, :json
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @profiles = Profile.all
  end
  
  def show
    @profile = Profile.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(resource)
    render 'shared/error_messages', :resource => resource
  end

  def flash_messages
    flash.collect do |key, msg|
      content_tag(:p, msg, :id => key, :class => "flash-message")
    end.join.html_safe
  end

  def display_when_present(collection, &block)
    collection.present? ? capture(&block) : I18n.t("empty")
  end

  def favicon
    "<link rel=\"shortcut icon\" href=\"/images/favicon.png\" />".html_safe
  end
  
  def analytics(site_id)
    html = <<-ANALYTICS
    <script>
     var _gaq = [['_setAccount', '#{site_id}'], ['_trackPageview']];
     (function(d, t) {
      var g = d.createElement(t),
          s = d.getElementsByTagName(t)[0];
      g.async = true;
      g.src = '//www.google-analytics.com/ga.js';
      s.parentNode.insertBefore(g, s);
     })(document, 'script');
    </script>
    ANALYTICS
    
    html.html_safe
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/admin/profiles/_form.html.erb
<%= stylesheet_link_tag('common/wmd.css') %>

<%= form_for([:admin, @profile]) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div id="wmd-editor" class="wmd-panel">
    <div id="wmd-button-bar" style="margin:0; padding:0 !important;"></div>
    <%= f.text_area :description, :id => "wmd-input", :rows => 20 %>
  </div>
  

  <div class="field">
    <%= f.label :race %><br />
    <%= f.text_field :race %>
  </div>
  <div class="field">
    <%= f.label :sex %><br />
    <%= f.text_field :sex %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= javascript_include_tag("common/wmd/wmd.js") %>
<%= javascript_include_tag("common/wmd/showdown.js") %>

app/views/admin/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/admin/profiles/index.html.erb
<h2>Listing profiles</h2>

<ul class="list">
<% @profiles.each do |profile| %>
  <%= content_tag_for :li, profile, :class => cycle(:odd, :even) do %>

   <h5><%= profile.name.titleize %></h5>
   <em>( <%= time_ago_in_words profile.created_at %> )</em>

    <div class="right">
      <%= link_to 'Edit', edit_admin_profile_path(profile) %> |
      <%= link_to 'Destroy', admin_profile_path(profile), :confirm => 'Are you sure?', :method => :delete %>
    </div>
  <% end %>
<% end %>
</ul>

<hr class="thick" />

<%= link_to 'New Profile', new_admin_profile_path, :class => 'button' %>

app/views/admin/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_profiles_path %>

app/views/admin/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @profile.name %>
</p>

<p>
  <b>Description:</b>
  <%= @profile.description %>
</p>

<p>
  <b>Race:</b>
  <%= @profile.race %>
</p>

<p>
  <b>Sex:</b>
  <%= @profile.sex %>
</p>


<%= link_to 'Edit', edit_admin_profile_path(@profile) %> |
<%= link_to 'Back', admin_profiles_path %>

app/views/home/index.html.erb
<h1>Homepage</h1>

<%= link_to 'public', profiles_path %>
<%= link_to 'private', admin_profiles_path %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Superfolio</title>
  <%= stylesheet_link_tag "admin/admin" %>
  <%= javascript_include_tag "common/jquery.min.js", "common/jquery-ui.min.js" %>
  <%= javascript_include_tag "rails", "admin/admin" %>
  <%= favicon %>
  <%= csrf_meta_tag %>

</head>
<body>

  <div id="wrapper">

    <div id="sidebar">
      <%= menu :id=>"main_menu", :class=>"menu" do |m| %>
        <%= m.profiles "Profiles", admin_profiles_path %> 
      <% end %>
    </div>

    <%= menu :id=>"secondary_menu", :class=>"menu" do |m| %>
      <%= m.logout "#{destroy_user_session_path}" do %>
        <%= image_tag "icon_docs.png" %> Log out
      <% end %>
    <% end %>

    <div id="content">

      <div class="box_container">
        <div class="box_inner_container">
          <div class="box">
            <%= yield :submenu %>

             <div class="box_body">
               <%= flash_messages %>

               <%= yield %>
             </div>
             <br/>
          </div>
        </div><!-- end .box_inner_container -->
      </div> <!-- end .box_container -->

    </div> <!-- end #content -->
  </div> <!-- end #wrapper -->

  <%= analytics "UA-19159130-1" %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Title <%= yield(:title) %></title>
  <%= favicon %>

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag  "vendor/jquery", "vendor/jquery-ui", "vendor/jquery.placeholder", "rails" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <!--[if lte IE 7]>
  <script defer type="text/javascript" src="js/pngfix.js"></script>

  <div class="notSupportedBrowser important">
    <p>
      <strong>Seu navegador está desatualizado. Baixe a nova versão
      <%= link_to image_tag("ua_ie.jpg", :class => "middle"),
            "http://www.microsoft.com/windows/internet-explorer", :target => "_blank" %>
      ou escolha outro suportado:</strong>
      <%= link_to image_tag("ua_ff.jpg", :class => "middle"), "http://www.mozilla.com/", :target => "_blank" %>
      <%= link_to image_tag("ua_sf.jpg", :class => "middle"), "http://www.apple.com/safari/", :target => "_blank" %>
      <%= link_to image_tag("ua_ch.jpg", :class => "middle"), "http://www.google.com/chrome/", :target => "_blank" %>
      <%= link_to image_tag("ua_op.jpg", :class => "middle"), "http://www.opera.com/", :target => "_blank" %>
    </p>
  </div>
  <![endif]-->

  <div id="wrapper">
    <%= flash_messages %>
    <%= yield :layout %>
  </div>

  <%= yield :bottom %>
  <%= analytics "UA-XXXXX" %>
</body>
</html>

app/views/profiles/index.html.erb
<ul>
  <% @profiles.each do |profile| %>
    <li class="profile">

      <h5><%= profile.name %></h5>
      <p><%= profile.description %>
      <%= link_to profile.name, profile %>
    </li>
  <% end %>
</ul>

app/views/profiles/show.html.erb
<h1><%= @profile.name %></h1>


<p>
  <%= @profile.description %>
</p>


<%= link_to 'Back', profiles_path %>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= resource.errors.count %> error(s) prohibited this
      <%= resource.class.model_name.human %> from being saved:
    </h2>

    <ul>
    <% resource.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>